### ISSUE TITLE
[Fix] LocalPartitioning does not utilise parallelism

### ISSUE THREAD

**Issue by hkkenneth** [KHP-Informatics/turbo-laser#8]
In LocalConfiguration.partitionHandler() , need to call setTaskExecutor() on handler with a properly configured SimpleAsyncTaskExecutor.

**Comment by RichJackson** [comment]
fixed this

**Comment by hkkenneth** [comment]
Not fully resolved yet.. asked a question on stackoverflow http://stackoverflow.com/questions/40936889/spring-batch-multithreading-has-a-default-limit-of-10-implicitly

**Comment by afolarin** [comment]
This issue was moved to CogStack/cogstack#8

**Comment by afolarin** [comment]
This issue was moved to CogStack/cogstack#19
